Fc\SettingsBundle\Entity\Hive:
    type: entity
    table: setting_hive
    repositoryClass: Fc\SettingsBundle\Repository\HiveRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 32
            nullable: false
        description:
            type: text
            nullable: true
        definedAtHive:
            column: defined_at_hive
            type: boolean
            nullable: false

    oneToMany:
        cluster:
            targetEntity: Cluster
            mappedBy: hive

    lifecycleCallbacks: {  }